services:
  bot:
    image: ghcr.io/nfway/instantview-bot:latest
    container_name: instantviewbot
    restart: unless-stopped
    init: true
    env_file:
      - .env
    environment:
      CONTAINERIZED: "1"
      NODE_ENV: production
      TZ: Asia/Shanghai
    volumes:
      - ./.conf:/app/.conf
      - ./.docs:/app/.docs
    command: npm start
